name: my second pipeling

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: uptime
              run: uptime
            - name: OS type
              run: cat /etc/os-release

    test:
        runs-on: ubuntu-latest
        steps:
            - name: hello
              run: echohello
