name: my second pipeline

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check Out Code
              uses: actions/checkout@v4

            - name: Build the Image
              run: |
               docker build -t ${{secrets.DOCKER_USERNAME}}/dev-app-profiles . 
               docker build -t ${{secrets.DOCKER_USERNAME}}/dev-app-profiles:${{github.run_number}} .
            ## the first build will build the image and tag it as latest
            ## the second build will build the image and tag it with the build number. we can chose the build number or the sha. the sha is the build I.
            - name: docker login
              uses: docker/login-action@v4
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Push Image to DockerHub-Registery
              run: |
               docker push ${{secrets.DOCKER_USERNAME}}/dev-app-profiles
               docker push ${{secrets.DOCKER_USERNAME}}/dev-app-profiles:${{github.run_number}}

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: SSH to Linux-Server and run the Container
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.DEPLOY_HOST}}
                username: ${{ secrets.DEPLOY_SSH_USERNAME }}
                key: ${{ secrets.DEPLOY_KEY }}
                #port: ${{ secrets.DEPLOY_PORT }}
                script: |
                    docker rm -f porfolio || echo " no container found, skipping removal. "
                    docker run -d --name portfolio-app -p 8080:80 ${{secrets.DOCKER_USERNAME}}/dev-app-profiles .
              