name: my second pipeling

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check Out Code
              uses: actions/checkout@v4 #action is used in GitHub Actions workflows to check out (clone) your repository's code onto the runner machine, so the workflow can access it.

            - name: Build the Image
              run: docker build -t ceejayme/dev-app-profiles .
            
            - name: list the Image
              run: docker images

            